### ISSUE TITLE
bug: `let!` macro doesn't work in loop

### ISSUE THREAD

**Issue by bangedorrunt** [datwaft/nvim.conf#13] opened 2021-08-08 10:35 UTC
Code:

```fnl
;; Disable built-in plugins
(defn- disable-distribution-plugins []
       (let [built-ins [:netrw
                        :netrwPlugin
                        :netrwSettings
                        :netrwFileHandlers
                        :gzip
                        :zip
                        :zipPlugin
                        :tar
                        :tarPlugin
                        :getscript
                        :getscriptPlugin
                        :vimball
                        :vimballPlugin
                        :2html_plugin
                        :logipat
                        :rrhelper
                        :spellfile_plugin
                        :matchit]
             providers [:perl :python :python3 :node :ruby]]
         (each [_ v (ipairs built-ins)]
           (let [b (.. :loaded_ v)]
             (let! b 1)))
         (each [_ v (ipairs providers)]
           (let [p (.. :loaded_ v :_provider)]
             (let! p 0)))))

(disable-distribution-plugins)
```

Expected behavior: all builtins and host-providers should be disable

Actual behavior: none of the above is set

Fix by using normal nvim api: `(tset vim.g p 0)` or `(tset vim.g b 1)`

**Comment by datwaft** [comment] 2021-08-08 16:48
This is kind of intended.

I talked about this with zest creator [here](https://reddit.com/r/neovim/comments/op39lf/_/h64ja0b/?context=1).

The problem is a limitation of macros, because they work on compilation time they cannot evaluate their parameters to know if a symbol (like `b` in your case) is a vim variable name or a local name (maybe it could be posible to read the local environment using a macro (I have seen it in fennel's documentation), but it would make the macro overly complicated).

Therefore, I needed to decide between using symbols as vim variables and not accepting runtime variables as names, or using strings and having the ability to do that.

**Option 1:**

```clojure
(let! spell true)
(let [spell "wrap"]
  (let! spell true)) ; this sets spell, not wrap
```

**Option 2:**

```clojure
(let! :spell true) ; now you need to use strings
(let! [spell "wrap"]
  (let! spell true)) ; sets wrap :D
```

At the moment, I decided to use **option 1**, because it looks a lot better.

Therefore, we have some options about how to solve this:
1. Modifying the macro to give priority to local variables if it finds them.
2. Creating a new macro with another name (e.g. `set~!`) that uses **option 2**.
3. Not using a macro for this, and just using `(tset vim.g <variable> <value>)`.

At the moment I am using option 3, because I created my macros for idiomatic vim configuration, and using loops and the like is more scripting, and for that I don't need it to be that idiomatic.

What do you think?

**Comment by bangedorrunt** [comment] 2021-08-08 20:41
Thank you for your explanation. I understand and totally I agree with your choice. But please add more information about this issue (in macro explanation docs?) for new users just like me who don't have an in depth knowledge at first about how macros works behind the curtain so mistake and/or confusion could be avoided 😀

**Comment by datwaft** [comment] 2021-08-09 16:30
Yes, I will close this issue when I add that to the documentation.

Thanks!

**Comment by datwaft** [comment] 2021-08-09 20:42
I added the explanation to the documentation, I will now close this issue.

**Closed as completed by datwaft** 2021-08-09 20:42 UTC
